# Generated by Django 5.1.2 on 2024-10-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('part_number', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('footprint_ref', models.CharField(max_length=255)),
                ('footprint_path', models.TextField()),
                ('library_ref', models.CharField(max_length=255)),
                ('library_path', models.TextField()),
                ('component_links', models.ManyToManyField(blank=True, to='db_components.componentlink')),
                ('suppliers', models.ManyToManyField(blank=True, to='db_components.supplier')),
            ],
        ),
    ]
