# Generated by Django 5.1.2 on 2024-11-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_components', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='component_links',
        ),
        migrations.RemoveField(
            model_name='component',
            name='suppliers',
        ),
        migrations.DeleteModel(
            name='ComponentLink',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
