# Generated by Django 5.1.2 on 2024-11-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_components', '0002_remove_component_component_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericComponent',
            fields=[
                ('partid', models.AutoField(db_column='PartId', primary_key=True, serialize=False)),
                ('part_number', models.CharField(db_column='Part Number', max_length=250)),
                ('comment', models.CharField(db_column='Comment', max_length=250)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
